"""CanvasComposer -- canvas-first poster painting for TMNF stadium-car skins.

This module hosts the central class :class:`CanvasComposer` which orchestrates
the new (canvas-first) skin pipeline.  Compared to the previous per-UV-island
pipeline, the rules of engagement are:

* The Diffuse is composed on a flat 2048x2048 RGBA *canvas*.  You paint
  motifs across the entire surface; UV islands are not used as masks during
  composition, only as a final blackout (so hidden polygons stay black).
* The Details (4096x4096) inherits the template's mechanical detail except
  for a small set of canonical "paintable" regions (wheel rim, suit, visor)
  which are recolored with the theme's accent colors.
* The whole skin shares a single alpha value chosen from
  :class:`MaterialFinish` (MATTE / DEFAULT / WET / GLOSS / CHROME).
* All known wordmark / branding regions in the template (CH "CAVERN
  HUNTERS" logo, KACKY label, WHEELHAND debug text, etc.) are blacked
  out so that we never inherit any copyrighted text.

The composer is intentionally small (<400 lines) and contains *no*
preset-specific logic; presets live in :mod:`skins.canvas_compose.motifs`
and are passed in as Motif objects.

Usage:

    from skins.canvas_compose import CanvasComposer, MaterialFinish
    from skins.canvas_compose.motifs import Gradient, BrushStreaks

    cc = CanvasComposer(theme_name="Aurora", seed=42)
    cc.paint(Gradient(stops=[...]))
    cc.paint(BrushStreaks(palette=[...]))
    cc.recolor_details({"rim_inner": (60, 200, 255), "suit_chest": (200,255,255)})
    cc.set_finish(MaterialFinish.DEFAULT)
    out_zip = cc.save(Path("out/Aurora.zip"))
"""
from __future__ import annotations

import io
import json
import zipfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Dict, List, Optional, Sequence, Tuple

import numpy as np
from PIL import Image, ImageFilter

# Reuse our existing DDS encoder.
from tmnf_dds import build_dds_dxt1_bytes, build_dds_dxt5_bytes  # type: ignore

from .finish import MaterialFinish
from .tyre_patch import patch_tyre_blocks

# ---------------------------------------------------------------------------
# Constants -- pulled from the May-2026 forensic study of CH_2026.zip.
# ---------------------------------------------------------------------------

# Canonical base template (mesh + driver + mechanical details).  Every skin
# we ship uses this exact mesh, which is byte-identical to MINA's mesh.
DEFAULT_TEMPLATE = Path(__file__).resolve().parents[2] / "assets" / "base_car" / "CH_2026.zip"

DIFFUSE_SIZE = 2048
DETAILS_SIZE = 4096

# Precomputed branding mask for the template Details.dds (4096^2).
# Was generated by analysing CH_2026.zip's Details.dds: every bright text-like
# connected component (WHEELHAND, OVERWALL, KACKY, skulls, sponsor marks)
# is True; rim spokes and decorative suit stripes are False.  See
# tools/build_branding_mask.py for the generator script.  The Diffuse needs
# no equivalent because we paint a brand-new canvas (never inherit CH /
# CAVERN HUNTERS text from the template).
BRANDING_MASK_PATH = (Path(__file__).resolve().parents[2]
                      / "assets" / "base_car" / "branding_mask_details.png")

# Canonical bboxes of paintable accents in the template Details.dds.  Each
# region keeps its existing template LUMINANCE shape (so reflections /
# shading / glove stitching stays intact) but is multiplied by the caller-
# supplied tint.  Coordinates were derived from the May-2026 forensic
# intersection of four reference skins (Liquicity / Aqua / Spring-2024 /
# MINA-2023) on the CH_2026 template.  Module-level (not a dataclass field)
# so it stays static across instances.
DETAILS_PAINTABLE: Dict[str, Tuple[int, int, int, int]] = {
    # Wheel rim interior (top-left wheel disc).
    "rim_inner":   (180, 65, 700, 580),
    # Driver suit chest (right-side cluster).
    "suit_chest":  (3010, 2090, 3700, 2660),
    # Helmet visor (top of driver cluster).
    "helmet_visor":(3070, 2020, 3460, 2090),
    # Driver gloves (bottom-right cluster).
    "gloves":      (3120, 3050, 3460, 3320),
    # Chassis / suspension / structural metal -- the WHOLE Details.dds
    # canvas.  Suspension wishbones, brake rotors, hex nuts, splitter,
    # cockpit walls, radiator and mudguard underside live in UV islands
    # scattered all over this canvas (not in one tidy rectangle), so we
    # paint the whole thing.  paint_chassis() automatically carves out
    # the driver-accent bboxes (rim_inner / suit_chest / helmet_visor /
    # gloves) so subsequent recolor_details() calls still operate on
    # their original luminance shape.  Tyre regions are protected by
    # the byte-level tyre_patch in save(), not by a paint-time mask.
    "chassis":     (0, 0, DETAILS_SIZE, DETAILS_SIZE),
}


# ---------------------------------------------------------------------------
# Motif protocol -- any object with a `.paint(rgba)` method works.
# ---------------------------------------------------------------------------

class Motif:
    """Base class -- subclasses implement `.paint(rgba, rng)`.

    Subclasses receive an *in-place* RGBA np.ndarray of shape (H, W, 4)
    and a :class:`np.random.Generator` so they remain deterministic.
    """
    name: str = "motif"

    def paint(self, rgba: np.ndarray, rng: np.random.Generator) -> None:  # pragma: no cover
        raise NotImplementedError


# ---------------------------------------------------------------------------
# Layer record (for transparency / debug / future re-ordering).
# ---------------------------------------------------------------------------

@dataclass
class _LayerRecord:
    name: str
    blend: str = "normal"
    opacity: float = 1.0
    motif: Optional[Motif] = None


# ---------------------------------------------------------------------------
# CanvasComposer
# ---------------------------------------------------------------------------

@dataclass
class CanvasComposer:
    """Build a TMNF skin by painting motifs onto a 2048x2048 canvas.

    Parameters
    ----------
    theme_name : str
        Used in the output filename (`CH_<theme_name>.zip`) and embedded in
        the manifest written into the zip.
    template_path : Path, optional
        Source zip with the mesh + driver Details.  Defaults to
        :data:`DEFAULT_TEMPLATE` (CH_2026.zip).
    seed : int
        Master RNG seed; passed to every motif's `.paint()`.
    base_color : tuple[int,int,int]
        Background fill for the Diffuse canvas (pre-motif).  Default is
        very dark navy so that pre-paint pixels never read as pure white.
    """

    theme_name: str
    template_path: Path = DEFAULT_TEMPLATE
    seed: int = 0
    base_color: Tuple[int, int, int] = (4, 5, 9)

    # Internal state -- populated as you call .paint() / .recolor_details().
    _layers: List[_LayerRecord] = field(default_factory=list)
    _diffuse_rgba: Optional[np.ndarray] = None
    _details_rgba: Optional[np.ndarray] = None
    _finish: MaterialFinish = MaterialFinish.DEFAULT
    _template_bytes: Dict[str, bytes] = field(default_factory=dict)
    # Per-pixel finish override -- a list of (bool_mask, alpha_value)
    # entries.  Used by :meth:`selective_finish_on_color` to make a
    # subset of Diffuse pixels render with a different finish than
    # the global ``_finish`` value (e.g. cyan stroke pixels = MATTE,
    # so they render with full saturation while the surrounding body
    # keeps its CHROME mirror finish).  Applied in :meth:`save` AFTER
    # the global ``diff[..., 3] = self._finish`` write, so later
    # entries override earlier ones at overlapping pixels.
    _finish_overrides: List[Tuple[np.ndarray, int]] = field(default_factory=list)
    # Underglow: when set, ProjShad.dds is recoloured so the projected
    # "shadow" reads as a coloured glow on the ground (see RFC-style
    # community tutorials from 2008 -- hue-shift the projection shadow).
    _underglow_color: Optional[Tuple[int, int, int]] = None
    _underglow_intensity: float = 1.0
    # Details dirty-flag -- starts False; flipped True by every method
    # that writes to ``self._details_rgba`` (paint_chassis,
    # paint_wheel_*, kill_stock_white_features, recolor_details, ...).
    # When False at save() time, the original template Details.dds is
    # emitted verbatim -- bypasses the lossy DXT5 round-trip that
    # otherwise drifts ~4-5 MB of chassis / wheel-rim / mudguard bytes
    # even when the canvas content is identical to the template.
    # Builders that never touch Details (e.g. LiveryComposer) thus
    # inherit byte-identical chassis + tyres without needing the
    # block-level tyre_patch at all.
    _details_dirty: bool = False

    # ------------------------------------------------------------------
    # Construction helpers
    # ------------------------------------------------------------------

    def __post_init__(self) -> None:
        if not self.template_path.exists():
            raise FileNotFoundError(f"Template zip not found: {self.template_path}")

        # Cache all template files in memory; we'll pick what we need at save().
        with zipfile.ZipFile(self.template_path) as z:
            for info in z.infolist():
                self._template_bytes[info.filename] = z.read(info.filename)

        for needed in ("Diffuse.dds", "Details.dds", "MainBody.Solid.Gbx",
                       "MainBodyHigh.Solid.Gbx", "ProjShad.dds", "Icon.dds"):
            if needed not in self._template_bytes:
                raise RuntimeError(f"Template missing required file: {needed}")

        # Fresh diffuse canvas, dark base.
        canvas = np.zeros((DIFFUSE_SIZE, DIFFUSE_SIZE, 4), dtype=np.uint8)
        canvas[..., 0] = self.base_color[0]
        canvas[..., 1] = self.base_color[1]
        canvas[..., 2] = self.base_color[2]
        canvas[..., 3] = int(self._finish)
        self._diffuse_rgba = canvas

        # Decode the template Details once -- it remains our base layer
        # for the mechanical/driver detail map.
        det_img = Image.open(io.BytesIO(self._template_bytes["Details.dds"])).convert("RGBA")
        self._details_rgba = np.array(det_img)

    # ------------------------------------------------------------------
    # Public painting API
    # ------------------------------------------------------------------

    def paint(self, motif: Motif, *, name: Optional[str] = None) -> "CanvasComposer":
        """Apply a motif to the Diffuse canvas (in place).

        Motifs may freely write across the full 2048x2048 area; no UV
        masks are applied during composition.  The order in which paint()
        is called is the bottom-to-top layer order.
        """
        if self._diffuse_rgba is None:
            raise RuntimeError("Composer not initialised.")
        layer_name = name or getattr(motif, "name", motif.__class__.__name__)
        # Deterministic per-layer seed.
        sub_seed = self.seed * 1_000_003 + len(self._layers) * 9967
        rng = np.random.default_rng(sub_seed)
        motif.paint(self._diffuse_rgba, rng)
        self._layers.append(_LayerRecord(name=layer_name, motif=motif))
        return self

    def set_finish(self, finish: MaterialFinish) -> "CanvasComposer":
        """Choose the global alpha value applied to every Diffuse pixel.

        See :class:`MaterialFinish` for the canonical values and what they
        look like in-game.
        """
        self._finish = finish
        return self

    def selective_finish_on_color(
        self,
        target_color: Tuple[int, int, int],
        *,
        tolerance: int = 80,
        finish: MaterialFinish = MaterialFinish.MATTE,
    ) -> "CanvasComposer":
        """Override the global Diffuse finish on pixels close to ``target_color``.

        Background
        ----------
        In TMNF Stadium, ``Diffuse.dds`` alpha is the per-pixel finish/
        specular map (NOT transparency).  The composer normally writes
        a single uniform alpha value across the whole atlas via
        :meth:`set_finish`.  That uniform write makes every painted
        stroke share the global finish -- so a body set to ``CHROME``
        (alpha 255) renders every stroke as mirror-reflective, which
        multiplies the stroke's RGB by the dark Stadium environment
        and visibly desaturates saturated colours like pure cyan.

        Wheel rims (painted on ``Details.dds``) escape this problem
        because the stock CH_2026 Details.dds has alpha=0 EVERYWHERE
        (confirmed by direct audit of ``assets/base_car/CH_2026.zip``),
        i.e. matte / no env reflection.  Pure cyan there renders as
        roughly ``(0, 220, 220) * lambert`` -- the bright LED look.

        This method gives the same matte treatment to selected pixels
        on the BODY: it records a boolean mask of "pixels whose RGB
        is within ``tolerance`` of ``target_color``" plus a
        replacement alpha.  At :meth:`save` time, after the uniform
        ``set_finish`` alpha is written, the mask is re-applied so
        the marked pixels get the override alpha instead.  Multiple
        calls stack -- later calls win at overlapping pixels.

        Use case
        --------
        Bright accent strokes on a chrome body:
            cc.set_finish(MaterialFinish.CHROME)   # body = mirror
            cc.paint(Streamline(palette=[(0,255,255)], ...))
            cc.selective_finish_on_color(
                (0, 255, 255), tolerance=80,
                finish=MaterialFinish.MATTE,
            )
        After save, the cyan strokes render at full saturation, the
        rest of the body keeps its chrome mirror finish.

        Parameters
        ----------
        target_color
            ``(R, G, B)`` of the strokes you want matte.
        tolerance
            Euclidean RGB distance used to decide if a pixel "matches"
            the target colour.  Default 80 catches anti-aliased edge
            pixels and slightly-darkened-by-blend stroke pixels while
            keeping unrelated body colours out of the mask.
        finish
            :class:`MaterialFinish` whose ``IntEnum`` value becomes
            the override alpha for matching pixels.  Default
            ``MATTE`` (alpha 100); pass ``CHROME``, ``DEFAULT``, etc.
            for other looks.
        """
        if self._diffuse_rgba is None:
            raise RuntimeError("Composer not initialised.")
        diff = self._diffuse_rgba
        target = np.array(target_color, dtype=np.int32)[None, None, :]
        delta = diff[..., :3].astype(np.int32) - target
        dist = np.sqrt((delta ** 2).sum(axis=2))
        mask = dist <= float(tolerance)
        if not mask.any():
            return self
        self._finish_overrides.append((mask, int(finish)))
        return self

    def selective_finish_on_hue_score(
        self,
        *,
        hue_score: str,
        threshold: int = 100,
        finish: MaterialFinish = MaterialFinish.MATTE,
    ) -> "CanvasComposer":
        """Override Diffuse finish on pixels with a strong hue score.

        Robust alternative to :meth:`selective_finish_on_color` when
        strokes blend non-uniformly with the background.  Anti-aliased
        stroke edges produce pixels like ``(0, 80, 80)`` for a cyan
        stroke on black -- the RGB Euclidean distance from pure cyan
        ``(0, 255, 255)`` is ~250, way above any usable tolerance,
        but the pixel is still chromatically cyan.

        Hue-score uses channel arithmetic to detect dominance:

        cyan    : ``max(G + B - 2*R, 0)``   -- green/blue over red
        magenta : ``max(R + B - 2*G, 0)``   -- red/blue over green
        yellow  : ``max(R + G - 2*B, 0)``   -- red/green over blue
        red     : ``max(2*R - G - B, 0)``   -- red over green/blue
        green   : ``max(2*G - R - B, 0)``
        blue    : ``max(2*B - R - G, 0)``

        Per-pixel: ``mask = (score >= threshold)``.  Score range is
        0..510.  Threshold suggestions:

        * 50  -- very permissive, catches faint halos and deep blends
        * 100 -- balanced default, catches medium-saturated strokes
        * 200 -- only saturated stroke cores

        Parameters
        ----------
        hue_score
            One of ``'cyan'``, ``'magenta'``, ``'yellow'``, ``'red'``,
            ``'green'``, ``'blue'``.  Selects the channel-arithmetic
            formula above.
        threshold
            Minimum score for a pixel to be included in the override
            mask.  See suggestions above.
        finish
            :class:`MaterialFinish` -- the override alpha value for
            matching pixels.
        """
        if self._diffuse_rgba is None:
            raise RuntimeError("Composer not initialised.")
        rgb = self._diffuse_rgba[..., :3].astype(np.int32)
        r, g, b = rgb[..., 0], rgb[..., 1], rgb[..., 2]
        scores = {
            "cyan":    np.maximum(g + b - 2 * r, 0),
            "magenta": np.maximum(r + b - 2 * g, 0),
            "yellow":  np.maximum(r + g - 2 * b, 0),
            "red":     np.maximum(2 * r - g - b, 0),
            "green":   np.maximum(2 * g - r - b, 0),
            "blue":    np.maximum(2 * b - r - g, 0),
        }
        if hue_score not in scores:
            raise ValueError(
                f"hue_score must be one of {sorted(scores)}; got {hue_score!r}"
            )
        score = scores[hue_score]
        mask = score >= int(threshold)
        if not mask.any():
            return self
        self._finish_overrides.append((mask, int(finish)))
        return self

    # ------------------------------------------------------------------
    # Details.dds selective recolor
    # ------------------------------------------------------------------

    def recolor_details(self, tints: Dict[str, Tuple[int, int, int]],
                        *, lum_threshold: int = 60) -> "CanvasComposer":
        """Tint the canonical paintable Details regions.

        Each entry in `tints` is `region_name -> (R, G, B)`.  The bounding
        box defines a search area; only pixels whose template luminance is
        at least `lum_threshold` get repainted (so dark gaps between
        parts stay dark and we don't bleed colour into the surrounding
        panel).

        Algorithm: MULTIPLICATIVE tint, normalised to the requested colour
        at average luminance.  This keeps the bright/dark structure of the
        template (rim spokes stay bright, stitching stays dark) while
        recolouring the hue everywhere in the region.

            new_pixel = colour * (lum / mean(lum))

        so the spokes (very bright) become a brighter version of the
        tint, and the inner-rim disc (medium) becomes the pure tint.

        Unrecognised region names are skipped silently.
        """
        if self._details_rgba is None:
            raise RuntimeError("Composer not initialised.")
        det = self._details_rgba
        self._details_dirty = True
        for region, color in tints.items():
            bbox = DETAILS_PAINTABLE.get(region)
            if bbox is None:
                continue
            x0, y0, x1, y1 = bbox
            crop = det[y0:y1, x0:x1, :3].astype(np.float32)
            lum = 0.299 * crop[..., 0] + 0.587 * crop[..., 1] + 0.114 * crop[..., 2]
            mask = lum >= lum_threshold
            if not mask.any():
                continue
            r, g, b = color
            color_arr = np.array([r, g, b], dtype=np.float32)
            sub_lum = lum[mask]
            ref = max(sub_lum.mean(), 1.0)
            # Multiplicative tint: spokes stay bright, mids hit the colour exactly.
            scale = sub_lum / ref           # 1.0 at mean, >1 for bright, <1 for dark
            new_rgb = color_arr[None, :] * scale[:, None]
            new_rgb = np.clip(new_rgb, 0, 255).astype(np.uint8)
            for c in range(3):
                channel = det[y0:y1, x0:x1, c]
                channel[mask] = new_rgb[:, c]
                det[y0:y1, x0:x1, c] = channel
        return self

    # ------------------------------------------------------------------
    # Details.dds chassis / suspension painting (system-wide theme
    # inheritance -- Truchet-style full-pattern stamp)
    # ------------------------------------------------------------------

    # Default exclusion regions for paint_chassis -- bboxes that subsequent
    # recolor_details() calls operate on.  We keep their original luminance
    # so the multiplicative tint in recolor_details still has the correct
    # template shape to work with.
    _CHASSIS_AUTO_EXCLUDE = ("rim_inner", "suit_chest", "helmet_visor", "gloves")

    def paint_chassis(self, *, strength: float = 1.0,
                      lum_threshold: int = 18,
                      exclusion_bboxes: Optional[Sequence[Tuple[int, int, int, int]]] = None,
                      include_driver_accents: bool = False,
                      blur_sigma: float = 40.0,
                      min_scale: float = 0.55,
                      ) -> "CanvasComposer":
        """Stamp the current Diffuse canvas across the whole Details.dds.

        Without this call, a finished skin inherits MINA's stock dark-grey
        suspension wishbones, brake rotors, brackets, splitter and cockpit
        interior from :data:`DEFAULT_TEMPLATE`.  In-game that reads as
        "the body is my skin, but the suspension is MINA's skin".
        ``paint_chassis()`` copies the same design that lives on the body
        into every chassis UV island, so the WHOLE car reads as one
        unified piece -- the approach Truchet_Maze and stained_glass take.

        How it works
        ------------
        * Reads the current Diffuse canvas (whatever motifs you've painted
          onto it so far) at 2048x2048.
        * **Blurs** the canvas (Gaussian, sigma=``blur_sigma``) into a
          low-frequency version BEFORE stamping.  Suspension wishbones,
          brake links and splitter bars are extremely thin UV strips
          (5-10 px wide) -- if we stamp the high-frequency body Voronoi
          straight onto them, the GPU samples 1-2 cells per strip and
          the result reads as random colour speckle.  Blurring smooths
          the pattern into bigger colour zones that read coherently
          even on thin strips while preserving the overall palette
          flow of the body design.
        * Resizes the blurred canvas to the chassis bbox -- which by
          default is the WHOLE 4096x4096 Details.dds because suspension
          / brake / structural UV islands sit scattered across the canvas
          (not in a single rectangle).
        * For each chassis pixel, multiplies the Diffuse color by the
          original Details luminance scale ``(lum / mean_lum)``, with a
          floor of ``min_scale`` so dark suspension bars (template lum
          ~25-35) still get a visibly-colored stamp instead of darkening
          to near-black.  This preserves the 3D shape (bright rivets
          stay bright) while keeping the chassis recognisably coloured.
        * Pixels darker than ``lum_threshold`` are kept stock (so black
          gaps between UV islands stay black).
        * Automatically carves out the driver-accent bboxes
          (``rim_inner``, ``suit_chest``, ``helmet_visor``, ``gloves``)
          so a subsequent :meth:`recolor_details` call still operates on
          the original luminance shape.  Pass
          ``include_driver_accents=True`` to overpaint these too.
        * Optional ``exclusion_bboxes`` (in 4096-space coords) protect
          additional sub-regions you don't want painted (e.g. gauges,
          brake caliper red).
        * ``strength`` < 1.0 blends the result back over the original
          Details so you can soften the stamp; ``strength=1.0`` is full
          Truchet / stained_glass behaviour.

        Parameter tuning
        ----------------
        - ``blur_sigma=0.0`` reverts to the pre-2026-05-18 raw-pattern
          stamp.  Higher values (60+) give an even smoother "wash" feel.
        - ``min_scale=1.0`` reverts to no floor (pure multiplicative
          tint, which was the bug that produced black suspension).
        - ``min_scale=0.0`` lets the darkest pixels go to black.

        Order of calls
        --------------
        Call AFTER all :meth:`paint` motif layers (so the Diffuse canvas
        is final) and BEFORE :meth:`recolor_details` (so suit/visor/
        gloves accents land on top of the chassis stamp).

        Tyre invariant safety
        ---------------------
        :meth:`save` re-applies a byte-level tyre patch after DXT5
        encoding, so wheel-disc / tread / sidewall blocks remain
        byte-identical to ``CH_2026.zip`` regardless of how much of the
        Details canvas you paint here.
        """
        if self._diffuse_rgba is None or self._details_rgba is None:
            raise RuntimeError("Composer not initialised.")
        bbox = DETAILS_PAINTABLE.get("chassis")
        if bbox is None:
            return self
        x0, y0, x1, y1 = bbox
        cw, ch = x1 - x0, y1 - y0
        det = self._details_rgba
        self._details_dirty = True

        # Take the (final) Diffuse, optionally blur it heavily so thin
        # UV strips don't read as high-freq speckle, then resize to
        # the chassis bbox.
        diff_rgb = self._diffuse_rgba[..., :3].astype(np.float32)
        if blur_sigma > 0:
            from scipy.ndimage import gaussian_filter
            for c in range(3):
                diff_rgb[..., c] = gaussian_filter(
                    diff_rgb[..., c], sigma=blur_sigma, mode="reflect")
        diff_pil = Image.fromarray(np.clip(diff_rgb, 0, 255).astype(np.uint8),
                                   "RGB").resize((cw, ch), Image.LANCZOS)
        diff_resized = np.array(diff_pil, dtype=np.float32)

        crop = det[y0:y1, x0:x1, :3].astype(np.float32)
        lum = 0.299 * crop[..., 0] + 0.587 * crop[..., 1] + 0.114 * crop[..., 2]
        mask = lum >= lum_threshold

        # Build the full exclusion list: auto-excludes (driver accents) +
        # caller-supplied bboxes.  Coordinates are in 4096-space so we
        # translate to chassis-local.
        all_excl: List[Tuple[int, int, int, int]] = []
        if not include_driver_accents:
            for key in self._CHASSIS_AUTO_EXCLUDE:
                ebx = DETAILS_PAINTABLE.get(key)
                if ebx is not None:
                    all_excl.append(ebx)
        if exclusion_bboxes:
            all_excl.extend(exclusion_bboxes)
        for ex0, ey0, ex1, ey1 in all_excl:
            lx0 = max(0, ex0 - x0); lx1 = max(0, min(cw, ex1 - x0))
            ly0 = max(0, ey0 - y0); ly1 = max(0, min(ch, ey1 - y0))
            if lx1 > lx0 and ly1 > ly0:
                mask[ly0:ly1, lx0:lx1] = False

        if not mask.any():
            return self

        sub_lum = lum[mask]
        ref = max(float(sub_lum.mean()), 1.0)
        # Floor on the luminance scale so dark suspension bars
        # (template lum ~25-35) still get a visibly-coloured stamp
        # rather than darkening to near-black under the multiply.
        scale = np.maximum(sub_lum / ref, float(min_scale))[:, None]
        stamp = np.clip(diff_resized[mask] * scale, 0, 255)
        orig = crop[mask]
        s = float(np.clip(strength, 0.0, 1.0))
        blended = (1.0 - s) * orig + s * stamp

        for c in range(3):
            channel = det[y0:y1, x0:x1, c]
            channel[mask] = np.clip(blended[:, c], 0, 255).astype(np.uint8)
            det[y0:y1, x0:x1, c] = channel
        return self

    # ------------------------------------------------------------------
    # Tyre-invariant override -- paint a contrast ring on the wheel disc.
    # Callers MUST also pass preserve_tyre_invariant=False to save().
    # ------------------------------------------------------------------

    def paint_wheel_disc_fill(
        self,
        color: Tuple[int, int, int],
        *,
        radius: int = 490,
        centre: Tuple[int, int] = (1161, 506),
        feather: int = 3,
        opacity: float = 1.0,
    ) -> "CanvasComposer":
        """Flood-fill the entire wheel-disc circle with a solid colour.

        Use this BEFORE painting LED rings (or any other accent) on
        the disc.  CH_2026's stock Details.dds has many bright white
        features baked into the wheel-disc UV (~50% of the disc
        circle's pixels are >180 luminance):

        * radial spoke "tickmark" stripes at r=163..330
        * a wide stock outline band at r=460..493 (~91k white px)

        Thin LED rings (e.g. radius 470 width 14) only cover a narrow
        slice and let the rest of those white features leak through
        the chrome material's specular highlights -- the wheel reads
        as a faded grey ring from middle / distant camera positions
        even when close-up pixel sampling shows magenta.

        This method paints a SOLID disc that obliterates every stock
        white feature, giving the LED ring on top a uniformly dark
        canvas to glow against.  Caller MUST pass
        ``preserve_wheel_disc=False`` to :meth:`save` for the fill to
        survive the tyre invariant patch.

        Parameters
        ----------
        color
            Base disc colour at full opacity.  Pick a dark, slightly
            desaturated relative of the LED hue (e.g. (50, 10, 50)
            dark magenta for a magenta LED) so the disc reads as
            "shadowed magenta surface", not "magenta paint".
        radius
            Outer radius of the fill in Details.dds pixel space.
            Default 490 stays just inside the disc UV edge (498), so
            the feather can't bleed onto adjacent UV islands.
        centre
            (x, y) centre of the disc.  ``(1161, 506)`` = OUTER face,
            ``(280, 1265)`` = INNER brake-rotor face.
        feather
            Pixels of soft edge at the disc rim to avoid a hard
            1-pixel boundary.
        opacity
            Blend amount over existing disc pixels (0..1).  Default
            1.0 = full coverage (white stock features completely
            replaced).  Lower values keep some stock luminance for
            a "tinted-stock" look.
        """
        assert self._details_rgba is not None, "Details canvas not ready"
        det = self._details_rgba
        self._details_dirty = True
        cx, cy = centre
        h, w = det.shape[:2]
        r_outer = radius + feather
        x0 = max(0, cx - r_outer)
        y0 = max(0, cy - r_outer)
        x1 = min(w, cx + r_outer + 1)
        y1 = min(h, cy + r_outer + 1)
        ys, xs = np.ogrid[y0:y1, x0:x1]
        dist = np.sqrt((xs - cx) ** 2 + (ys - cy) ** 2)
        if feather > 0:
            mask = np.clip((radius + feather - dist) / feather,
                           0.0, 1.0) * opacity
        else:
            mask = (dist <= radius).astype(np.float32) * opacity
        if mask.max() <= 0.0:
            return self
        m = mask[..., None]
        patch = det[y0:y1, x0:x1, :3].astype(np.float32)
        fill_rgb = np.array(color, dtype=np.float32)[None, None, :]
        blended = patch * (1.0 - m) + fill_rgb * m
        det[y0:y1, x0:x1, :3] = np.clip(blended, 0, 255).astype(np.uint8)
        return self

    def kill_stock_white_features(
        self,
        replace_color: Tuple[int, int, int] = (30, 8, 40),
        *,
        threshold: int = 160,
        protect_tread: bool = True,
        protect_sidewall: bool = False,
        protect_wheel_disc: bool = False,
    ) -> "CanvasComposer":
        """Obliterate every remaining bright stock feature on Details.dds.

        CH_2026's Details.dds bakes a *lot* of small white / near-white
        features into the wheel-adjacent UV islands beyond just the
        disc face:

        * **Fender arc** (the big C-shape at approx (350..1500,
          1700..1980)) -- the white rim on its inner curve wraps
          around the OUTER PERIMETER of the rendered tyre in 3D and
          shows as a thin white outline framing each wheel from any
          camera angle, even after the disc face is solid-filled.
        * **Octagonal hub cap** at (~720, 1280) -- white bolt circle.
        * **Hexagonal hub cap** at (~840, 1265) -- white rim trim.
        * Misc small stencil text / hub bolt heads scattered in the
          right column of Details.dds.

        Individually masking each of these is fragile (the bboxes
        aren't documented anywhere), so this method takes the
        sledgehammer approach: scan the entire Details.dds for any
        pixel that's near-white (luminance above ``threshold`` AND
        no channel below ``threshold * 0.8`` to avoid affecting
        coloured-but-bright pixels like saturated LED magenta) and
        replace it with ``replace_color``.

        The tread rectangle is protected by default because the
        rubber road-contact surface must stay byte-identical to
        baseline (its grey is below the threshold anyway, but
        explicit guard against future threshold changes).  Sidewall
        and wheel disc are NOT protected by default -- callers using
        :meth:`paint_sidewall_fill` / :meth:`paint_wheel_disc_fill`
        already overpainted those regions with darker colour, so the
        threshold check naturally skips them.

        Order of calls
        --------------
        Call AFTER :meth:`paint_chassis`, :meth:`paint_wheel_disc_fill`,
        :meth:`paint_sidewall_fill`, :meth:`recolor_details`, and any
        LED-ring layers, so this scoops up only the leftover stock
        features.  Calling earlier would also kill the intentional
        white tints (helmet rim trim, etc.) you actually want.

        Parameters
        ----------
        replace_color
            (R, G, B) to write over each bright pixel.  Pick something
            dark and in the theme palette (e.g. dark magenta
            ``(30, 8, 40)`` for a magenta-themed skin).
        threshold
            Per-channel minimum to count a pixel as "stock white".
            Default 160 catches near-whites without eating
            saturated coloured pixels (e.g. (255, 30, 230) magenta has
            G=30 << 160 so it's not affected).
        protect_tread
            If True (default), the tread rect (0,0)-(640,960) is
            forced to skip even if bright.
        protect_sidewall, protect_wheel_disc
            Optional opt-in guards if the caller wants to preserve
            stock features in those regions.
        """
        assert self._details_rgba is not None, "Details canvas not ready"
        det = self._details_rgba
        self._details_dirty = True
        rgb = det[..., :3]
        lum = rgb.mean(axis=2)
        soft_thresh = threshold * 0.8
        bright = (lum > threshold) & (rgb.min(axis=2) > soft_thresh)

        if protect_tread:
            bright[0:960, 0:640] = False
        else:
            # If the caller is intentionally painting the tread, do NOT
            # un-paint it -- the dark theme fill is below the threshold
            # anyway, but skip to be explicit.
            pass
        if protect_sidewall:
            bright[1430:1560, 50:1380] = False
        if protect_wheel_disc:
            cx, cy, r = 1161, 506, 498
            h, w = det.shape[:2]
            y0 = max(0, cy - r); y1 = min(h, cy + r + 1)
            x0 = max(0, cx - r); x1 = min(w, cx + r + 1)
            ys = np.arange(y0, y1)[:, None]
            xs = np.arange(x0, x1)[None, :]
            in_disc = (ys - cy) ** 2 + (xs - cx) ** 2 <= r * r
            bright[y0:y1, x0:x1] &= ~in_disc

        det[bright, :3] = replace_color
        return self

    def paint_tread_fill(
        self,
        color: Tuple[int, int, int],
        *,
        rect: Tuple[int, int, int, int] = (0, 0, 640, 960),
        opacity: float = 1.0,
    ) -> "CanvasComposer":
        """Flood-fill the tyre tread UV rectangle with a solid colour.

        The tread (0,0)-(640,960) on Details.dds is the CIRCUMFERENTIAL
        rubber surface that contacts the road -- the wide round outer
        face of each tyre.  CH_2026's stock tread is a uniform dark
        grey (~lum 6) so painting it doesn't add visible content; the
        '4 horizontal bars' the user sees on the rendered tyre are
        actually MESH-baked ridges (or specular highlights on the
        cylindrical geometry under chrome material), NOT texture
        features.  Painting the tread therefore tints the rubber but
        doesn't remove the geometric bars.

        Useful when you want the rubber to read as themed (e.g. dark
        magenta to match the disc) instead of stock grey, so the
        residual specular bands at least bounce in-theme rather than
        as off-coloured highlights.  Caller MUST pass
        ``preserve_tread=False`` to :meth:`save` for the fill to
        survive the tyre invariant patch.
        """
        assert self._details_rgba is not None, "Details canvas not ready"
        det = self._details_rgba
        self._details_dirty = True
        x0, y0, x1, y1 = rect
        h, w = det.shape[:2]
        x0 = max(0, x0); y0 = max(0, y0)
        x1 = min(w, x1); y1 = min(h, y1)
        if x1 <= x0 or y1 <= y0:
            return self
        patch = det[y0:y1, x0:x1, :3].astype(np.float32)
        fill_rgb = np.array(color, dtype=np.float32)[None, None, :]
        blended = patch * (1.0 - opacity) + fill_rgb * opacity
        det[y0:y1, x0:x1, :3] = np.clip(blended, 0, 255).astype(np.uint8)
        return self

    def paint_sidewall_fill(
        self,
        color: Tuple[int, int, int],
        *,
        rect: Tuple[int, int, int, int] = (50, 1430, 1380, 1560),
        opacity: float = 1.0,
    ) -> "CanvasComposer":
        """Flood-fill the tyre sidewall UV rectangle with a solid colour.

        CH_2026's sidewall strip (50, 1430) -> (1380, 1560) carries
        vertical groove patterns that wrap into a ring of
        circumferential ridges around the cylindrical side face of
        each tyre.  Viewed from the side, those ridges catch the
        Stadium environment's specular highlight and read as a thin
        lighter horizontal "tread band" running across the rubber --
        the user-visible "horizon bar" complaint.

        Painting the strip with a uniform dark colour (no grooves)
        wraps into a perfectly smooth dark cylinder side, killing the
        horizon bar entirely.  Caller MUST pass
        ``preserve_sidewall=False`` (or ``preserve_tyre_invariant=
        False`` with explicit ``preserve_sidewall=False``) to
        :meth:`save` for the fill to survive the tyre invariant
        patch.

        Parameters
        ----------
        color
            Solid (R, G, B) for the sidewall.  Default-stock rubber
            is around (33, 30, 33); a slightly darker version like
            (12, 8, 14) reads as "deep black rubber" without going
            pure black (pure black flattens against the dark
            environment background).
        rect
            (x0, y0, x1, y1) of the sidewall UV strip.  Default is
            the canonical CH_2026 sidewall bbox.
        opacity
            Blend amount over existing pixels (0..1).
        """
        assert self._details_rgba is not None, "Details canvas not ready"
        det = self._details_rgba
        self._details_dirty = True
        x0, y0, x1, y1 = rect
        h, w = det.shape[:2]
        x0 = max(0, x0); y0 = max(0, y0)
        x1 = min(w, x1); y1 = min(h, y1)
        if x1 <= x0 or y1 <= y0:
            return self
        patch = det[y0:y1, x0:x1, :3].astype(np.float32)
        fill_rgb = np.array(color, dtype=np.float32)[None, None, :]
        blended = patch * (1.0 - opacity) + fill_rgb * opacity
        det[y0:y1, x0:x1, :3] = np.clip(blended, 0, 255).astype(np.uint8)
        return self

    def paint_wheel_disc_ring(
        self,
        color: Tuple[int, int, int],
        *,
        radius: int = 480,
        width: int = 14,
        opacity: float = 0.95,
        feather: int = 2,
        centre: Tuple[int, int] = (1161, 506),
    ) -> "CanvasComposer":
        """Paint a thin contrast ring on the Details.dds wheel-disc region.

        This deliberately writes INSIDE the tyre invariant zone, so the
        skin will no longer be byte-identical to ``CH_2026`` on the wheel
        disc.  Callers MUST pass ``preserve_tyre_invariant=False`` to
        :meth:`save` or the patch in save() will overwrite this ring.

        Parameters
        ----------
        color
            (R, G, B) of the ring at full opacity.
        radius
            Mid-radius of the annulus in Details.dds pixel space (4096
            ref).  Default 480 sits 18 px inside the wheel disc edge
            (which is at radius 498).
        width
            Annulus thickness in pixels.  Default 14.
        opacity
            Blend amount over the existing wheel-disc pixels (0..1).
        feather
            Number of pixels of soft edge on each side of the annulus
            to avoid a hard 1-pixel boundary.
        centre
            (x, y) centre of the ring in Details.dds 4096 coords.
            Default ``(1161, 506)`` is the OUTER wheel disc centre
            (matches ``tyre_patch.py``).  Pass ``(280, 1265)`` to paint
            the INNER (chassis-facing) brake-rotor disc UV instead --
            useful for skins that want both faces of the wheel to show
            the same LED hoop.
        """
        assert self._details_rgba is not None, "Details canvas not ready"
        det = self._details_rgba
        self._details_dirty = True
        cx, cy = centre
        h, w = det.shape[:2]
        # Local bbox around the disc.
        r_outer = radius + width // 2 + feather
        x0 = max(0, cx - r_outer)
        y0 = max(0, cy - r_outer)
        x1 = min(w, cx + r_outer + 1)
        y1 = min(h, cy + r_outer + 1)
        ys, xs = np.ogrid[y0:y1, x0:x1]
        dist = np.sqrt((xs - cx) ** 2 + (ys - cy) ** 2)
        half = width / 2.0
        # Soft annulus mask: full opacity within the band, feathered edges.
        if feather > 0:
            outer_soft = np.clip((radius + half + feather - dist) / feather,
                                 0.0, 1.0)
            inner_soft = np.clip((dist - (radius - half - feather)) / feather,
                                 0.0, 1.0)
            mask = np.minimum(outer_soft, inner_soft) * opacity
        else:
            in_band = (dist >= radius - half) & (dist <= radius + half)
            mask = in_band.astype(np.float32) * opacity
        if mask.max() <= 0.0:
            return self
        m = mask[..., None]
        patch = det[y0:y1, x0:x1, :3].astype(np.float32)
        ring_rgb = np.array(color, dtype=np.float32)[None, None, :]
        blended = patch * (1.0 - m) + ring_rgb * m
        det[y0:y1, x0:x1, :3] = np.clip(blended, 0, 255).astype(np.uint8)
        return self

    def set_underglow_color(
        self,
        color: Optional[Tuple[int, int, int]],
        *,
        intensity: float = 1.0,
    ) -> "CanvasComposer":
        """Enable a coloured 'underglow' projection beneath the car.

        Trackmania Stadium projects ``ProjShad.dds`` straight down onto
        the ground using a multiply-style blend.  The stock texture is
        a black-on-white silhouette of the chassis + four wheel blobs,
        so the projection darkens the ground = a fake shadow.

        Replace BLACK in that texture with a saturated colour and the
        same projection now tints the ground with that colour wherever
        the shadow would have fallen -- reads as a neon underglow halo
        beneath the car.  This is the canonical TMNF underglow recipe
        documented in community tutorials since 2008
        (``http://tm-tutorials.blogspot.com/2008/07/custom-neons.html``):
        hue-shift the projection shadow texture.

        Parameters
        ----------
        color
            (R, G, B) of the underglow at full shadow coverage.  Pass
            ``None`` to disable (default behaviour: stock dark shadow
            passed through unchanged).
        intensity
            How strongly black maps to ``color``.  1.0 = full hue swap
            (black -> color), <1.0 leaves some darkness for a duller
            glow, >1.0 steepens the coverage curve so even partially
            shadowed pixels jump to full glow colour (brighter,
            wider-feeling underglow halo).  Capped at 4.0 to avoid
            ringing artefacts at the projection edge.  White pixels
            are always preserved (no projection).
        """
        self._underglow_color = color
        self._underglow_intensity = float(max(0.0, min(4.0, intensity)))
        return self

    def _build_underglow_projshad_bytes(self) -> Optional[bytes]:
        """Recolour the template ProjShad.dds to produce coloured underglow.

        Returns ``None`` if no underglow is configured -- caller should
        fall through to the unchanged template ProjShad.
        """
        if self._underglow_color is None:
            return None
        raw = self._template_bytes.get("ProjShad.dds")
        if raw is None:
            return None

        # Decode the template ProjShad via Pillow's DDS reader.
        proj = Image.open(io.BytesIO(raw)).convert("RGBA")
        arr = np.array(proj, dtype=np.float32)
        rgb = arr[..., :3]
        # Inverse luminance -> "shadow coverage" map (white=0, black=1).
        # Use simple mean because the stock texture is grayscale.
        coverage = (255.0 - rgb.mean(axis=2)) / 255.0
        coverage = np.clip(coverage * self._underglow_intensity, 0.0, 1.0)
        # Interpolate WHITE (no projection) -> underglow colour as
        # shadow coverage increases.  Multiply-blend on the ground
        # then turns into a coloured tint at the shadow shape.
        target = np.array(self._underglow_color, dtype=np.float32)
        white = np.array([255.0, 255.0, 255.0], dtype=np.float32)
        cov3 = coverage[..., None]
        new_rgb = white * (1.0 - cov3) + target * cov3
        new_rgba = np.zeros_like(arr)
        new_rgba[..., :3] = np.clip(new_rgb, 0, 255)
        new_rgba[..., 3] = 255
        new_img = Image.fromarray(new_rgba.astype(np.uint8), mode="RGBA")
        return build_dds_dxt1_bytes(new_img, mipmaps=True)

    def paint_wheel_led_glow(
        self,
        color: Tuple[int, int, int],
        *,
        radius: int = 470,
        halo_width: int = 26,
        halo_feather: int = 11,
        halo_opacity: float = 0.55,
        main_width: int = 14,
        main_feather: int = 2,
        main_opacity: float = 1.0,
        core_width: int = 5,
        core_feather: int = 1,
        core_opacity: float = 0.95,
        core_white_mix: float = 0.85,
        kill_outer_band: bool = True,
        outer_band_radius: int = 491,
        outer_band_width: int = 14,
        centre: Tuple[int, int] = (1161, 506),
    ) -> "CanvasComposer":
        """Paint a layered LED-glow hoop on the wheel disc.

        Produces the "neon LED ring" look (e.g. modern EV concept-car
        wheels): a wide soft halo to fake specular bloom, a sharp
        saturated main ring as the LED itself, and a thin white-tinted
        core that reads as the "hot wire" inside the LED.

        All four stages stay strictly inside the wheel-disc UV bounds
        (max radius ~497).  Caller must still pass
        ``preserve_wheel_disc=False`` to :meth:`save` for the rings to
        survive the tyre invariant patch.

        Parameters
        ----------
        color
            Base saturated RGB of the LED (e.g. magenta (255, 50, 200)
            or cyan (0, 255, 255)).
        radius
            Mid-radius of the LED hoop in Details.dds pixel space.
            Default 470 -- with halo_width=26 + halo_feather=11 the
            outermost halo pixel sits at radius 494, comfortably
            inside the disc circle (radius 498) so the feather
            never leaks onto adjacent UV islands and projects onto
            tyre rubber.
        halo_*
            Wide soft outer band -- fakes specular bloom bleed.
        main_*
            Sharp saturated colour band -- the LED proper.
        core_*
            Thin white-tinted band at the centre of the LED -- reads
            as the hot wire inside.
        core_white_mix
            Fraction of white to mix into ``color`` for the core
            (0 = pure colour, 1 = pure white).  0.85 default produces
            a near-white pastel that retains a hint of the base hue.
        kill_outer_band
            If True (default), stamp a fourth opaque ring at the
            disc's outermost paintable band (radius ~491, width 14)
            to obliterate the stock white "tyre outer-edge" stripe
            baked into CH_2026.  Without this kill ring the white
            stripe leaks through the halo's low-opacity feather and
            shows up in 3D as a thin pale "horizon" line running
            around the tyre.  Set False only if you want to preserve
            the stock white outline for some aesthetic reason.
        outer_band_radius, outer_band_width
            Geometry of the kill ring.  Defaults (491, 14) place the
            ring at r=484..498 = exactly over the white stripe and
            butted against the disc UV's outer edge.
        centre
            (x, y) centre of the LED hoop.  Default ``(1161, 506)``
            is the OUTER wheel disc.  Pass ``(280, 1265)`` to paint
            the INNER (chassis-facing) brake-rotor disc instead.
            The inner-disc UV is smaller, so callers should also
            reduce ``radius`` (e.g. ~185), the band widths, and the
            outer_band geometry accordingly.
        """
        # 1. Outer halo -- wide, soft, low opacity (specular bloom fake).
        self.paint_wheel_disc_ring(
            color=color, radius=radius, width=halo_width,
            opacity=halo_opacity, feather=halo_feather, centre=centre,
        )
        # 2. Main saturated ring -- the LED itself.
        self.paint_wheel_disc_ring(
            color=color, radius=radius, width=main_width,
            opacity=main_opacity, feather=main_feather, centre=centre,
        )
        # 3. White-tinted core -- "hot wire" inside the LED.
        r, g, b = color
        core_color = (
            int(r + (255 - r) * core_white_mix),
            int(g + (255 - g) * core_white_mix),
            int(b + (255 - b) * core_white_mix),
        )
        self.paint_wheel_disc_ring(
            color=core_color, radius=radius, width=core_width,
            opacity=core_opacity, feather=core_feather, centre=centre,
        )
        # 4. Outer-band kill -- nuke the stock white outline ring.
        if kill_outer_band:
            self.paint_wheel_disc_ring(
                color=color, radius=outer_band_radius,
                width=outer_band_width, opacity=1.0, feather=2,
                centre=centre,
            )
        return self

    def paint_inner_wheel_led_glow(
        self,
        color: Tuple[int, int, int],
        *,
        radius: int = 185,
        halo_width: int = 14,
        halo_feather: int = 6,
        halo_opacity: float = 0.55,
        main_width: int = 7,
        main_feather: int = 1,
        main_opacity: float = 1.0,
        core_width: int = 3,
        core_feather: int = 1,
        core_opacity: float = 0.95,
        core_white_mix: float = 0.85,
        kill_outer_band: bool = False,
    ) -> "CanvasComposer":
        """Paint a scaled-down LED hoop on the INNER wheel-disc face.

        TMNF wheels have TWO disc UV islands: an OUTER face at canvas
        (1161, 506) radius 498, and an INNER (chassis-facing) face --
        a brake-rotor pattern at approximately (280, 1265) with rotor
        outer radius ~200.  When viewed from the side, you typically
        see ONE face per wheel; without this method, the inner face
        is just stock brake-disc detail (or paint_chassis bleed) with
        no LED hoop, so the two sides look very different.

        This method stacks the same halo + main + core layers as
        :meth:`paint_wheel_led_glow` but at the inner-disc centre and
        with smaller default geometry (radius 185 = just inside the
        rotor rim at ~200).  ``kill_outer_band`` is False by default
        because the inner-disc UV has no equivalent stock white ring.

        Parameters mirror :meth:`paint_wheel_led_glow`; see that
        docstring for layer semantics.
        """
        self.paint_wheel_led_glow(
            color=color,
            radius=radius,
            halo_width=halo_width, halo_feather=halo_feather,
            halo_opacity=halo_opacity,
            main_width=main_width, main_feather=main_feather,
            main_opacity=main_opacity,
            core_width=core_width, core_feather=core_feather,
            core_opacity=core_opacity,
            core_white_mix=core_white_mix,
            kill_outer_band=kill_outer_band,
            centre=(280, 1265),
        )
        return self

    # ------------------------------------------------------------------
    # Save -- write the final zip.
    # ------------------------------------------------------------------

    def save(self, out_path: Path, *,
             preserve_tyre_invariant: bool = True,
             preserve_wheel_disc: Optional[bool] = None,
             preserve_sidewall: Optional[bool] = None,
             preserve_tread: Optional[bool] = None) -> Path:
        """Finalise the skin and write to `out_path`.

        Parameters
        ----------
        out_path
            Destination zip path.
        preserve_tyre_invariant
            If True (default), the tyre/wheel-disc/sidewall DXT5 blocks
            in the final Details.dds are restored byte-for-byte from the
            ``CH_2026`` template -- guarantees the audit script passes
            in full.  Set to False to allow some/all regions to drift.
            ``preserve_wheel_disc`` / ``preserve_sidewall`` provide
            finer control per region.
        preserve_wheel_disc
            Granular override that takes precedence over the global
            flag for the wheel-disc region only.  Use ``False`` to let
            the disc be painted (e.g. outer-face contrast ring) while
            still locking the rubber tread + sidewall to baseline.  If
            ``None``, follows ``preserve_tyre_invariant``.
        preserve_sidewall
            Granular override for the tyre sidewall strip (50, 1430)
            -> (1380, 1560).  Use ``False`` to let the sidewall be
            painted -- typically to flood-fill a solid colour over
            the stock vertical groove pattern that wraps into a
            visible horizontal "tread bar" on the rubber when viewed
            from the side.  If ``None``, follows
            ``preserve_tyre_invariant``.
        preserve_tread
            Granular override for the tyre tread rect (0, 0)
            -> (640, 960) -- the circumferential rubber road-contact
            surface.  Use ``False`` to allow theming the tread
            (e.g. dark magenta rubber instead of stock grey).  Note
            the visible "tread bars" around each tyre are GEOMETRIC
            (mesh-baked ridges + specular highlights on the curved
            rubber), so painting the tread tints them in-theme but
            does not eliminate them; mesh-level edits would be
            required for full removal.  If ``None``, follows
            ``preserve_tyre_invariant``.

        Returns the output path.  Steps:

        1.  Stamp the chosen :class:`MaterialFinish` into the Diffuse alpha
            channel (uniform).
        2.  Black-out all known wordmark/branding bboxes on Diffuse and
            Details -- no MINA / CH / KACKY signage in the output.
        3.  DXT5-encode Diffuse + Details, copy mesh / dirty / shadow files,
            and zip everything up.
        """
        if self._diffuse_rgba is None or self._details_rgba is None:
            raise RuntimeError("Composer not initialised.")

        diff = self._diffuse_rgba.copy()
        det  = self._details_rgba.copy()

        # 1) Uniform finish on the diffuse alpha.
        diff[..., 3] = int(self._finish)

        # 1b) Per-pixel finish overrides -- e.g. cyan-stroke pixels
        # painted with alpha=MATTE so they render at full saturation
        # while the surrounding body keeps its CHROME mirror finish.
        # See :meth:`selective_finish_on_color`.
        for mask, override_alpha in self._finish_overrides:
            diff[mask, 3] = override_alpha

        # 2) Blackout wordmarks on Details using the precomputed branding
        # mask.  Where the mask is set, we replace the pixel with the
        # average of nearby non-mask pixels, so text fades into its
        # surrounding panel tone (no obvious rectangles or patches).
        # Diffuse needs no equivalent: we paint a brand-new canvas, so no
        # CH / CAVERN HUNTERS text is ever present.
        if BRANDING_MASK_PATH.exists():
            brand = np.array(Image.open(BRANDING_MASK_PATH).convert("L")) > 127
            if brand.shape == det.shape[:2]:
                self._fill_mask_from_surround(det, brand)

        # 3) Encode + zip.
        diff_img = Image.fromarray(diff, "RGBA")
        det_img  = Image.fromarray(det,  "RGBA")

        diff_bytes = build_dds_dxt5_bytes(diff_img, mipmaps=True)

        # Details.dds short-circuit: if no Details-writing method was
        # ever called, the canvas content is byte-identical to the
        # template decoded into RGBA, but re-encoding it through DXT5
        # would drift ~4-5 MB of chassis / wheel-rim / mudguard
        # blocks (DXT5 is lossy even on a pristine round-trip).  Skip
        # the re-encode in that case and emit the template bytes
        # verbatim.  Tyre patch becomes a no-op (already byte-identical).
        base_det_bytes = self._template_bytes.get("Details.dds")
        if not self._details_dirty and base_det_bytes is not None:
            det_bytes = base_det_bytes
        else:
            det_bytes  = build_dds_dxt5_bytes(det_img,  mipmaps=True)

            # Tyre invariant: restore byte-identical wheel disc / tread /
            # sidewall blocks from the template's original Details.dds.
            # The DXT5 re-encode above is lossy (1-3 channel values of
            # drift even on unmodified pixels); this patch makes the
            # tyre region byte-for-byte equal to CH_2026.zip in every
            # mip level.  See skins/canvas_compose/tyre_patch.py.
            if base_det_bytes is not None:
                disc_flag = (preserve_tyre_invariant
                             if preserve_wheel_disc is None
                             else preserve_wheel_disc)
                swall_flag = (preserve_tyre_invariant
                              if preserve_sidewall is None
                              else preserve_sidewall)
                tread_flag = (preserve_tyre_invariant
                              if preserve_tread is None
                              else preserve_tread)
                if (preserve_tyre_invariant
                        or not disc_flag or not swall_flag or not tread_flag):
                    det_bytes = patch_tyre_blocks(
                        det_bytes, base_det_bytes,
                        include_disc=disc_flag,
                        include_tread=tread_flag,
                        include_sidewall=swall_flag,
                    )

        # Generate an Icon by resizing the Diffuse (sans wordmarks) -- gives a
        # natural-looking thumbnail without inheriting CH branding.
        icon = diff_img.resize((128, 128), Image.LANCZOS).convert("RGBA")
        icon_bytes = build_dds_dxt5_bytes(icon, mipmaps=True)

        out_path = Path(out_path)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        # If an underglow colour is configured, recolour the projection
        # shadow texture; otherwise pass the template's ProjShad through
        # unchanged.
        underglow_bytes = self._build_underglow_projshad_bytes()

        with zipfile.ZipFile(out_path, "w", zipfile.ZIP_DEFLATED) as z:
            z.writestr("Diffuse.dds", diff_bytes)
            z.writestr("Details.dds", det_bytes)
            z.writestr("Icon.dds", icon_bytes)
            if underglow_bytes is not None:
                z.writestr("ProjShad.dds", underglow_bytes)
            # Mesh + (stock shadow if no underglow) + dirty variants
            # pass through unchanged.
            pass_through = ["MainBody.Solid.Gbx", "MainBodyHigh.Solid.Gbx",
                            "DiffuseDirty.dds", "DetailsDirty.dds"]
            if underglow_bytes is None:
                pass_through.insert(2, "ProjShad.dds")
            for name in pass_through:
                if name in self._template_bytes:
                    z.writestr(name, self._template_bytes[name])
            # Manifest -- handy when debugging packs of generated skins.
            manifest = {
                "theme": self.theme_name,
                "seed": self.seed,
                "finish": self._finish.name,
                "finish_alpha": int(self._finish),
                "layers": [{"name": l.name} for l in self._layers],
            }
            z.writestr("skin.json", json.dumps(manifest, indent=2))
        return out_path

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _fill_mask_from_surround(arr: np.ndarray, mask: np.ndarray) -> None:
        """Replace `arr` pixels under `mask` with the mean of nearby non-mask pixels.

        Implementation: weighted-blur inpaint.  Zero out the masked signal,
        blur it, blur the keep-mask, divide -- each masked pixel ends up
        with the local average of valid pixels around it.  Uses
        :func:`scipy.ndimage.gaussian_filter` (this version of PIL refuses
        to blur "F" mode images on macOS).
        """
        from scipy.ndimage import gaussian_filter

        rgb = arr[..., :3].astype(np.float32)
        keep = (~mask).astype(np.float32)
        sigma = 6.0

        blur_sig = np.stack([
            gaussian_filter(rgb[..., c] * keep, sigma=sigma, mode="reflect")
            for c in range(3)
        ], axis=-1)
        blur_w = gaussian_filter(keep, sigma=sigma, mode="reflect")
        blur_w = np.clip(blur_w, 1e-3, None)
        avg = blur_sig / blur_w[..., None]

        rgb[mask] = avg[mask]
        arr[..., :3] = np.clip(rgb, 0, 255).astype(np.uint8)
        arr[..., 3] = 255

    # ------------------------------------------------------------------
    # Public introspection helpers
    # ------------------------------------------------------------------

    def get_diffuse(self) -> Image.Image:
        """Return a copy of the current Diffuse canvas as a PIL image."""
        assert self._diffuse_rgba is not None
        return Image.fromarray(self._diffuse_rgba.copy(), "RGBA")

    def get_details(self) -> Image.Image:
        """Return a copy of the current Details canvas as a PIL image."""
        assert self._details_rgba is not None
        return Image.fromarray(self._details_rgba.copy(), "RGBA")
